# Generated by Django 4.2.2 on 2023-07-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=30)),
                ("poster", models.ImageField(upload_to="images/movie-poster/")),
            ],
        ),
    ]
