# Generated by Django 4.2.2 on 2023-07-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_customuser_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(upload_to="media/movie-poster/"),
        ),
    ]
